# Generated by Django 3.2.5 on 2022-09-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue_book',
            name='status',
        ),
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('borrow', 'borrow')], default='active', max_length=10),
        ),
    ]
