# Generated by Django 3.2.5 on 2022-09-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20220922_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_book',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('borrow', 'borrow')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
